### ISSUE TITLE
Remixicons rendering GINORMOUS

### ISSUE THREAD

**Issue by menagerie198** [aidenlx/obsidian-icon-shortcodes#12]
![image](https://user-images.githubusercontent.com/7330436/141678329-39eef405-b400-42f1-8b44-48f39aeb7f82.png)
Is there anyway to resize icons?

**Comment by aidenlx** [comment]
does replacing styles.css with provided file helpful? 

[styles.css.zip](https://github.com/aidenlx/obsidian-icon-shortcodes/files/7533634/styles.css.zip)

**Comment by Liong1976** [comment]
The same thing happened to mine.

I am using Windows 10, Obsidian 0.13.2, and the icon only shows in Preview mode. Thanks

**Comment by aidenlx** [comment]
@Liong1976 @menagerie198 have you checked if `styles.css` is downloaded properly and try to use [this updated css](https://github.com/aidenlx/obsidian-icon-shortcodes/files/7533634/styles.css.zip) to see if it can be fixed?

**Comment by Liong1976** [comment]
It is still the same. And the icon only shows in Preview mode. I am using the Sanctum theme. But I had tried with no theme, Minimal theme, Prism, Purple Owl, and Shimmering Focus. The result was the same.

![image](https://user-images.githubusercontent.com/88898230/141784175-b695e71b-5d4f-40a0-b778-4d732a94e297.png)

**Comment by aidenlx** [comment]
should be fixed in [v0.4.2](https://github.com/aidenlx/obsidian-icon-shortcodes/releases/tag/0.4.2)

**Comment by menagerie198** [comment]
Good stuff! The sizing is now spot on, although I could only load the plugin via BRAT. Also, I only get a black version - i.e. the icon is only properly visible in a light theme. Is this to be expected/unavoidable?

**Comment by aidenlx** [comment]
> I only get a black version - i.e. the icon is only properly visible in a light theme. Is this to be expected/unavoidable?

You can use css to change color of a specific icon pack: https://stackoverflow.com/a/52041765
