### ISSUE TITLE
Feature: Import icon packs via pack.zip

### ISSUE THREAD

**Issue by aidenlx** [aidenlx/obsidian-icon-shortcodes#13]
Useful to provide icon pack on demand without bundling everything pack inside `main.js`

**Comment by alanalvarado** [comment]
Hey, can you add https://devicon.dev/

Thanks in advance.

**Comment by aidenlx** [comment]
@alanalvarado it's supported in latest beta v0.7.0 (obsidian insider v0.13.27 required)
