### ISSUE TITLE
Icons render on new line

### ISSUE THREAD

**Issue by swehba** [aidenlx/obsidian-icon-shortcodes#19]
It might be the theme I'm using, but when I insert an icon and then preview the note, the icon appears by itself on a new line. I am using the Obsidian Nord theme.

**Comment by aidenlx** [comment]
does it still occur in default theme? if it doesn't, you should probably go to theme repo to report issue.

**Comment by swehba** [comment]
Using Obsidian Nord theme:

- Here is what I see in [Editing Mode](https://cln.sh/intySH+) with Live Preview enabled.
- Here is what I see in [Reading Mode](https://cln.sh/OSXwQE+) with Live Preview enabled.

Using the default Obsidian theme:

- Here is what I see in [Reading Mode](https://cln.sh/63IBcw+) with Live Preview enabled.

Bottom line:

1. The icons render just fine in editing mode with or without Live Preview.
2. The icons render with extra lines in Obsidian Nord but not in the default Obsidian theme.

Unfortunately, Obsidian Nord is *the* most popular third-party theme. I will definitely contact the theme developer.

**Comment by swehba** [comment]
After updating the Obsidian Nord theme, all is well!
