### ISSUE TITLE
Support live preview

### ISSUE THREAD

**Issue by NomarCub** [aidenlx/obsidian-icon-shortcodes#21]
Icons could be rendered in live preview and turn to text only when clicked on.

**Comment by NomarCub** [comment]
Thanks!
Although I would expect icons to turn back to text when selected or clicked into, the way iframes, images, internal and external links work in live preview.

**Comment by aidenlx** [comment]
>  I would expect icons to turn back to text when selected or clicked into

I've made the decision of not showing text on selection is that I want to mimic the editing experience similar to emojis, and act like one character that can be skipped. you can have the shortcode shown in source mode and the icon will should at the right of shortcode, btw
