### ISSUE TITLE
Request: Twitter Emoji ?

### ISSUE THREAD

**Issue by I-Pch** [aidenlx/obsidian-icon-shortcodes#27]
Hi @aidenlx 😊 

Thank you for the plugin 🙌 ... Being a heavy user of emojis, it's very handy 😁 !

Would it be possible to implement [Twemoji](https://twemoji.twitter.com/) ([GitHub](https://github.com/twitter/twemoji)) as an alternative rendering (for the emojis) to the classical "device defined" ones 😊 ?

If not, that's not a big deal 😉 ...

**Comment by aidenlx** [comment]
duplicate of #18
