### ISSUE TITLE
Release missing

### ISSUE THREAD

**Issue by joethei** [aidenlx/obsidian-icon-shortcodes#28]
The release for 0.6.3 is missing, generating a error message when trying to update.

**Comment by aidenlx** [comment]
Sorry! forget to add that v0.6.3 is an API utils update only, as it only changes the published libs in npm. the published package no longer bundle everything together and let bundler in your plugin to handle them. what error did you encounter
exactly?

**Comment by joethei** [comment]
I am talking about the gh release
Normal users cannot download the plugin currently since the manifest points to 0.6.3.

**Comment by I-Pch** [comment]
I also encounter troubles trying to update the plugin 🤷‍♀️ ... 

<img width="458" alt="Failed to install" src="https://user-images.githubusercontent.com/77828085/154843249-1f165bc1-5059-4d13-b61d-4465f88435e5.png">

**Comment by aidenlx** [comment]
thanks! it should be fixed now. obviously it is automatic version bump that breaks this update... I will fix this in future release workflow
