### ISSUE TITLE
Adapt icons to theme / text color

### ISSUE THREAD

**Issue by NomarCub** [aidenlx/obsidian-icon-shortcodes#31]
By default most icons are in black (with Obsidian and Lucide icons that are the only ones available from the start both being this way), making them basically invisible in dark mode, which is Obsidian's default.
![image](https://user-images.githubusercontent.com/5298006/157136789-5f696924-7c32-487c-b46e-2a759647ae33.png)

I know there are workarounds to this (like mentioned in #12). But proper support for this would mean no tinkering needed from end users.

Icons could also take the color of link titles and whatever else text context they're in via currentColor, color or other properties.
Here the plus sign could be purple too, making it look more like it's part of the link's text.
![image](https://user-images.githubusercontent.com/5298006/157136582-1c056db4-8546-412a-ba6a-d9b9f86b86f2.png)

I know Lucide supports currentColor already and other providers probably also do, and there are ways to do it regardless.
Here's a [pointer](https://discord.com/channels/686053708261228577/702656734631821413/865318907832172555) to some other info about currentColor in Obsidian.

**Comment by aidenlx** [comment]
related to #23

**Comment by I-Pch** [comment]
I just want to add a big +1 to @NomarCub request 👍 😇

**Comment by aidenlx** [comment]
will be released in next version (when [this commit](https://github.com/aidenlx/obsidian-icon-shortcodes/commit/e9cd3c1f940732923d2d15124290910c8d57be7d) is merged to master branch)

**Comment by NomarCub** [comment]
The new release just dropped with this, thanks!

There are two edge cases I found right off the bat. Icons at the beginning and end of links get colored as normal text, not as the link color.
![image](https://user-images.githubusercontent.com/5298006/158851631-db2959a8-d92c-40fa-afff-45fe1d488561.png)

And the picker doesn't adapt at all.
![image](https://user-images.githubusercontent.com/5298006/158851719-0b0ac9de-d3ae-4789-b206-6da22f0a1dfc.png)

**Comment by aidenlx** [comment]
@NomarCub for links, it seems to be a problem of code mirror so there isn't too much I can help. for suggester, I've pushed v0.9.2 to fix this
