### ISSUE TITLE
Feature Request: Icons scaling with font

### ISSUE THREAD

**Issue by Relkion** [aidenlx/obsidian-icon-shortcodes#38]
It would be great if the icons scaled in size next to headings and such.
<img width="728" alt="Screen Shot 2022-03-18 at 1 45 34 AM" src="https://user-images.githubusercontent.com/101229519/158967566-f5fc1731-7b15-4ee6-9de0-f57e6feaa103.png">
thanks for making this. I've been looking for a replacement since the other icons plugin seems to have been abandoned.

**Comment by rossoj85** [comment]
I agree with this. Just installed this plugin after I had issues with another popular icon plugin not rendering icons in IOS. This enhancement would make this plugin perfect
