### ISSUE TITLE
[Bug] Putting an icon at the beginning of a header breaks it

### ISSUE THREAD

**Issue by Relkion** [aidenlx/obsidian-icon-shortcodes#44]
<img width="270" alt="Screen Shot 2022-04-09 at 7 45 47 PM" src="https://user-images.githubusercontent.com/101229519/162599023-c54b9934-98b7-4a5c-bf00-04fecc889929.png">

**Comment by aidenlx** [comment]
Can you upload the source markdown for the broken heading? I suppose that you are using `#:icon: Heading` instead of `# :icon:Heading`?

**Comment by Relkion** [comment]
You are absolutely right, adding another space fixed it. It was wrong of me to assume there was already a space there since one is required to activate the plugin. Thank you for your help!
