### ISSUE TITLE
CSS snippet format doesn't work on newer plugin version

### ISSUE THREAD

**Issue by spasticginger** [aidenlx/obsidian-icon-shortcodes#45]
Good afternoon!  

With the newest version, did the format change for custom CSS?  The following snippet (using the format on this GitHub page) no longer works in a Vault when using plugin version 0.9.3.  I've also tried just using '.isc-icon', instead of targeting a specific icon pack with no luck.  

I did verify it still works fine on an old Vault still using plugin version 0.8.4.

```
.isc-icon.isc-Neko {
  display: inline;
  height: 2em !important;
  width: 2em !important;
  vertical-align: middle;
}
```

**Comment by aidenlx** [comment]
sorry! I've forgot to update to doc, the update on inline render actually breaks the previous css snippet, this one should work: 
```css
.isc-icon.isc-Neko > img,
.isc-icon.isc-Neko > svg {
  height: 2em !important;
  width: 2em !important;
}

**Comment by spasticginger** [comment]
Worked like a charm!  Thank you so much!! 🙏
