### ISSUE TITLE
Better ordering of Emoji suggestions

### ISSUE THREAD

**Issue by GollyTicker** [aidenlx/obsidian-icon-shortcodes#47]
First of all, I and very thankful for this plugin :star: . I enjoy using emojis in my notes as the small images make some content more easily communicated.

However, during usage of the plugin, I noticed, that the order of the suggesting emojis when starting a shoartcode `:` is sub-optimal.

Consider these shortcodes: `star`, `heart`, `x` and `right`
When using the first three, I expect, that after typing it out, the top-most suggestion is the most specific one corresponding to it.
e.g. for `star` I expect the `star` :star: suggestion to be top-most. However, we see a different list:
![image](https://user-images.githubusercontent.com/4527862/167302195-5631e27d-9dbf-46cc-9913-43fa9beda261.png)

The same problem also appears with the other shortcodes.

![image](https://user-images.githubusercontent.com/4527862/167302229-48ce61f5-d1e2-424d-8307-238e5cee486f.png)

![image](https://user-images.githubusercontent.com/4527862/167302234-8155b9ba-913c-450f-93c0-e3015e5ef6b8.png)

This is less helpful, as sometimes we need to scroll down a lot to see the right emoji.

For the prefix `right`, we get these suggestions:
![image](https://user-images.githubusercontent.com/4527862/167302299-00d893a0-4dd1-43c7-bc9e-7eade799155c.png)

However, I think it's better, when shorter completions such as `arrow_right`, `fist_right` and `copyright` are higher prioritised than the other ones. Generally, if the suffix needed to complete the shortcode is short, then the emoji should be higher on the list.

And for the case of `x`, if the emoji is short alltogether and has a relatively large matching with the prefix shortcode, then it should be also higher on the list.

Most other existing emoji shortcode suggestion lists seem to return, what I would intuitively expect. For instance, when writing an issue comment, the github emojis suggest this:

![Screenshot from 2022-05-08 17-06-08](https://user-images.githubusercontent.com/4527862/167302589-2fbd1fb6-d9c0-457a-b856-8a542b2ed421.png)

![Screenshot from 2022-05-08 17-07-37](https://user-images.githubusercontent.com/4527862/167302585-501ed576-1441-4d77-b4ee-7258038ea750.png)

![Screenshot from 2022-05-08 17-06-52](https://user-images.githubusercontent.com/4527862/167302588-0205ec59-86cc-4f2e-9829-191c49c0b8b8.png)

Could we have the shortcodes prioritised differently?

What do you think? :star: 

If there is need, I could provide some help.

**Comment by GollyTicker** [comment]
Sorry, I made this issue in the wrong repository.

**Comment by aidenlx** [comment]
😂It's ok. Maybe you can try this plugin instead, it support emoji as well and provide better fuzzy search result: 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/31102694/167410502-9d4dea79-d179-4acb-85b8-db6438aab117.png">

**Comment by GollyTicker** [comment]
@aidenlx Honestly... You are right :smile: 

I tried your plugin and it does do this correctly. And furthermore, you've more features available.

I think, that more people could be using your plugin - but many people don't discover your plugin, since it does not have "emoji" in it's title. It gets lower prioritsed, when the following list is recommended:
![image](https://user-images.githubusercontent.com/4527862/167489508-9beb19e4-e9ca-4e8f-a21b-f96d9b2417de.png)

Given this list of suggestions, people would usually directly take the first or second plugin.

But as emoji's are a core feature of your's, why don't you add it to the title? :wink:

**Comment by aidenlx** [comment]
well basically because the plugin is design on top of emoji shortcode with additional support for custom icons, and I couldn't find a better name that includes emoji😂, and btw it's sorted by installed count so renaming it won't change the order here.
