### ISSUE TITLE
竟然是中国大佬开发的？后面会不会像obsidian_supercharged_link一样可以显示在链接里。

### ISSUE THREAD

**Issue by PencilMing** [aidenlx/obsidian-icon-shortcodes#50]
不知道后面有没有可能像[obsidian_supercharged_links](https://github.com/mdelobelle/obsidian_supercharged_links)一样或者联动，放到链接的形式里，那就完美了。现在用的地方会有些少。

**Comment by aidenlx** [comment]
你可以到他那里开个issue，我这是有API的
