### ISSUE TITLE
Icon Shortcodes not working on mobile

### ISSUE THREAD

**Issue by I-Pch** [aidenlx/obsidian-icon-shortcodes#53]
Hi there 😊 !

It's been a while since I used Obsidian on mobile but doing so today, I was a bit surprised to see that the icons I used in various admonitions were not rendered anymore in live preview... which I'm pretty sure wasn't the case before as I tried to "design" notes that would work (i.e.: be rendered/displayed in the same way) both on desktop and mobile.

I checked in the `Settings` -> `Community plugins` -> `Installed plugins` and discovered that `Icon shortcodes` is indeed disabled and while trying to enable it, I get a message telling me : 

```
Failed to load plugin obsidian-icon-shortcodes
```

I checked on iPhone & iPad Pro + Obsidian Mobile app `v1.2.2` with the same result 🤔 ...

So, wasn't Icon Shortcodes compatible with the Mobile app before ?
Did I dream it was ? 😅  (It could happened... As it really has been month since I needed to use the mobile app 😇 )

It would be a real bummer if that was the case and I can't use icon shortcodes on mobile but not such a big deal though 😇.

**Comment by aidenlx** [comment]
Seem like it’s mobile obsidian issue, which unexpectedly update icon shortcode to a version that only support upcoming obsidian version. I’ve opened an issue https://github.com/obsidianmd/obsidian-api/issues/73, meanwhile you can manually reinstall v0.9.5, which should work as expected.

**Comment by aidenlx** [comment]
Are you using obsidian sync to sync plugins? Maybe you’ve synced the wrong version from obsidian insider build? Can you try to reinstall plug-in on mobile and check if the installed version being v0.9.5?

**Comment by I-Pch** [comment]
> Are you using obsidian sync to sync plugins? 
I don't use Obsidian Sync 😊 ... My vault is on iCloud 😊 

> Maybe you’ve synced the wrong version from obsidian insider build? Can you try to reinstall plug-in on mobile and check if the installed version being v0.9.5?

I'm indeed using Insider builds both on Desktop and Mobile and I'm ashamed to say that I absolutely didn't think about some possible (API) incompatibility between Obsidian desktop (v0.15.3 - Insider build) and Obsidian mobile (v.1.2.2 (56) - Insider build) 🤦‍♀️ ... Sorry 😅 ! I know Obsidian Mobile is often a little bit behind in terms of development than the Desktop and I really should have thought about it before opening the issue 😅 ... 

I still un-installed ICS 0.9.6 and re-installed it on Mobile and it worked 😁 !
Obsidian Mobile Installed ICS 0.9.5 (instead of 0.9.6) which works perfectly 🙌 😁 !  

Sorry for the extra work I've put on your shoulder here but thank you for investigating this "problem" and helping me solving it 😁 !
